# Network
DEFAULT_IP_SERVER = '192.168.1.42'
DEFAULT_PORT = 5050
DEFAULT_TIMEOUT = 10

BUFFER_SIZE = 4096
FORMAT = 'utf-8'

COMMAND_CLIENT_CONNECT = "snake_connect"
COMMAND_CLIENT_DISCONNECT = "snake_exit"
